language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install ;
- v8_install ;
- dcmtk_install ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: NSMNrCJpFg/MMdwMmtFFtfYcc2I7BBAM+l98eK/cLoJAbfnLFuKEefpS6pu9aRa3/mQr1Q39u0BwW4H5Kfjc+7SxYDCgo1WInvrgzOZm2bvYr816rd59J4H4ya9osYlFFTu5gc9MDuyLLFd3bEIBb2sia4ur3fu2E6/lfQUcsqS1b4uX1DPAEVhX8Ydt80quZpxHjVgcg7tXkNG8YYfOUXYjU4sr+g8fquI9CEybqch9sspvayGGBd2/u7xT8wAwoO9SW0ywF6B6CDhPNvvLlz2f0FT+FnhKOdQKCJ7pqbKd2IJnT8VTstnw+ThNhefZnw9MwCDfNEBCGP9LrNbtKoiYMzwVE8RtsKcckU55aUN8+/fBbcPPZiY2W2/rrPsXlF1gFIJ5EISLY93G1BB8YDGYvqgIWBoo1qr2gXoU0tYKfishqkmzb1gJiZuan92dUQmF205b81oqB22EAK0B1OJX3va+PjOMiwN7WyFeAXD8rCF6rhZjhVbUJYxJVr4mTbI4QpICdRErWHQzaqtKJIWAUlazcXzWF8wvX57a9/G+AC1nxcG6TxlliErPwD5RkbAD3B39ebGke5uWu7X/3oUgnEt74oXUZKLOaEmV5uNUoMW/a+IGtBeHzBCAkfh4JSEb2+G8B4GF5oaJ7RpWyA1tN8/4pd7BTxOBpyf+EYU=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait
  100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
