language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: oRKPimdl/Y3rZRkALoQVm9aX+oZVBZSnxeT2lapL6s9GI3El2OAYxRQorqDNooE1TuYhrMgi+cv75bpNJLnGY2XQlDIW6HXNRPemm8gU81YAaBiHF66sTtmzgQ4MQiITl/59gVuAjIGqPb9Pat5MAIYGKMyLpJrdHMfMzRCDLJoTwGJCJdcxyRWHaUAQIyOk4c2G0fJIAgd9UjCgdRJ0ql5/VYR2Awyk5zxfX5c7mJQYBUNkLJ8hYEl1BeO/xCnONsBTBjRREANrQtNWqTY6F3sEDQXzbzBGqKOSE2MQ4+YOBZjW9uB4srezWu7yvP5C/NM3xL8AglfQczVOyjLPBYINC4mQ8gsp8Jn7p2rTQW18tqdHkWzQiRF6p1fZlWThGdj2srdoSwaoAxwMWY+KDE+Ve5dFc7T3FY1C8TCZqITJUgd25D/cdFjpqpe/IeNPqvIKNdkDb7Dm5bQmSimH4BqrIyv49S8zyYYURoFlskFwcIqEBptJeR0vg4jWSamtd/gXa9OfsVvBO4HForL0aIOK+ZPKkt7b69/9aX7U10uAk8a+/xWK34JyqqJJdq/Xk8ntVFHfmqf7avU7y8h+u6EFnjLAHoYR8HOxn6rgCJqND2ulD1s5QMxRSjM7GIzZGd1BDMn1OtP6dkhRTS5brg/IpSYTKQiaxneUlK2NO4g=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
