language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: e9tI5LssMcYCKJZeqtqZMbChFK9U4XEgMOrb7ErNO+/1BB57/1ne9EnqqlkJpC/zFFpMtBm9od/qCdhvdH80yjNvBMwbqEW1qNXYQnYXwXTR3cyvJEwsHoSl7NCHsX68V3FfW8z/yQdU3rCq3XJ+5E2URK7cb3EkU5agdcshIWZaNbFgjKf7AdOaKyRIoZXtEHYLcEhUlxove5cUmG3jC2EOaPJs8cj0UiBz+tgu9iMNAg83g/yMpJ9/SSCPykWYbGUCjhSQCb2dPbt2vPENd7Ue2KtukVylXn1GnHpR3fH7B/PZi0kiWUFPcUGrglN2IwcXGpR8/pF18ZYsagisaIzAYOrvbSLaYxMWXQXFKohS60GnlV1ulv/5PyD9nkuYI5iOPVem5WfLZ4A3mwhMu69bEGektkDpaI505uuIy1Z4KBQOT3cgdxSAsY/LdtwAfL6DGE9ZucbDPMhjWOrJYxut0il0Rgm+i/TboV4LOFnjoKZaHFNtT8+rZjsmjSHjFBZ23dTOd3weZ2TJTB47gUwHTIrrz7n4D0WJAZz5RHZdxTOElH0+MfayIx745jMFFc2OzbLe3IpTVCheoORq7LRj8p9AtljC3ynST0T11z9rp3X0rvQyH6PWrLKbdEC7q5Ej6NhdSpKRTZkk008r8gqjXEVJjTHYTeaYJjmvNtQ=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
